# Generated by Django 4.2.16 on 2024-09-18 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_day_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('muscle_group', models.CharField(choices=[('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('CHEST', 'Chest'), ('BACK', 'Back'), ('LEGS', 'Legs'), ('ABS', 'Abs'), ('STRETCHING', 'Stretching'), ('WARM_UP', 'Warm Up'), ('LATS', 'Lats'), ('HAMSTRING', 'Hamstring'), ('CALVES', 'Calves'), ('QUADRICEPS', 'Quadriceps'), ('TRAPEZIUS', 'Trapezius'), ('SHOULDERS', 'Shoulders'), ('GLUTES', 'Glutes')], default='Biceps', max_length=20)),
                ('calorie_lost', models.IntegerField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.day')),
            ],
        ),
    ]
