# Generated by Django 4.2.16 on 2024-09-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='calorie_lost',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='day',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
    ]
