# Generated by Django 4.2.16 on 2024-09-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_workout_calorie_lost_remove_workout_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='calorie_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
