# Generated by Django 4.2.16 on 2024-09-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_workout_calorie_lost_workout_day_workout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
