# Generated by Django 4.2.16 on 2024-09-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_meal_calories_meal_notes_workout_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='muscle_group',
            field=models.CharField(choices=[('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('CHEST', 'Chest'), ('BACK', 'Back'), ('LEGS', 'Legs'), ('ABS', 'Abs'), ('STRETCHING', 'Stretching'), ('WARM_UP', 'Warm Up'), ('LATS', 'Lats'), ('HAMSTRING', 'Hamstring'), ('CALVES', 'Calves'), ('QUADRICEPS', 'Quadriceps'), ('TRAPEZIUS', 'Trapezius'), ('SHOULDERS', 'Shoulders'), ('GLUTES', 'Glutes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
