# Generated by Django 4.2.16 on 2024-09-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_workout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='muscle_group',
            field=models.CharField(choices=[('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('CHEST', 'Chest'), ('BACK', 'Back'), ('LEGS', 'Legs'), ('ABS', 'Abs'), ('STRETCHING', 'Stretching'), ('LATS', 'Lats'), ('HAMSTRING', 'Hamstring'), ('CALVES', 'Calves'), ('QUADRICEPS', 'Quadriceps'), ('TRAPEZIUS', 'Trapezius'), ('SHOULDERS', 'Shoulders'), ('GLUTES', 'Glutes')], max_length=20),
        ),
    ]
