# Generated by Django 4.2.16 on 2024-09-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_meal_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='meal_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
