# Generated by Django 4.2.16 on 2024-09-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_remove_newuser_meal_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='meal_goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
