# Generated by Django 4.2.16 on 2024-09-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_remove_newuser_meal_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
